language: node_js
node_js:
  - 6
  - 4

before_install:
  - rm npm-shrinkwrap.json

branches:
  only:
  - master

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev

sudo: required
dist: trusty
