# Where things are
destination:  ./_site
layouts_dir:  _layouts
data_dir:     _data
includes_dir: _includes
collections:
  posts:
    output:   true

# Handling Reading
include:      []
exclude:      ["node_modules", "package.json"]
keep_files:   []
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Serving
baseurl: "" # does not include hostname
show_dir_listing: false

# Outputting
permalink:     {SLUSH{=permalink}}
paginate_path: /page:num
timezone:      {SLUSH{=timezone}}

quiet:    false
verbose:  false
defaults: []

liquid:
  error_mode: lax

# Markdown Processors
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1

# Html Compressor
compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: ['dev']
  blanklines: false
  profile: false
  startings: []
